import json
import logging
import time
import threading
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Tuple, Dict, List, Any, Set

# Configure log output formatting
logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger("SmartSIEM.Engine")

class AlertSeverity(Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

@dataclass
class SiemLog:
    """Represents a normalized security event log within the pipeline."""
    log_id: str
    tenant: str
    timestamp: int  # Epoch millisecond timestamp
    service: str
    event_type: str
    payload: Dict[str, Any]
    tags: Set[str] = field(default_factory=set)

    def get_field(self, path: str, default: Any = None) -> Any:
        """Extracts nested properties using dot-notation string paths."""
        keys = path.split('.')
        val = self.payload
        for key in keys:
            if isinstance(val, dict) and key in val:
                val = val[key]
            else:
                return default
        return val

@dataclass
class SiemAlert:
    """Represents an analytical security incident generated by a correlation rule matching."""
    alert_id: str
    title: str
    description: str
    severity: AlertSeverity
    creation_time: int
    rule_name: str
    triggering_log: SiemLog
    mitre_tactics: List[str] = field(default_factory=list)
    mitre_techniques: List[str] = field(default_factory=list)
    aggr_key: Optional[str] = None
    aggr_limit: Optional[int] = None

class SiemRule(ABC):
    """Abstract Base Class establishing structural interface standards for SIEM detection rules."""
    
    def __init__(self, name: str, description: str, service: str):
        self.name = name
        self.description = description
        self.service = service
        self.templates: Dict[str, str] = {"en": "Default alert template"}
        self.tenant_mapping: Dict[str, str] = {}

    @abstractmethod
    def evaluate(self, log: SiemLog) -> Optional[Tuple[SiemAlert, Optional[Dict[str, Any]]]]:
        """Processes a log entry to determine if alert thresholds are satisfied."""
        pass

    def get_localized_description(self, tenant: str, defaults: str) -> str:
        lang = self.tenant_mapping.get(tenant, "en")
        return self.templates.get(lang, defaults)

# =====================================================================
# RULE REPO: STATEFUL AND STATELESS IMPLEMENTATIONS
# =====================================================================

class BruteForceAuthRule(SiemRule):
    """Tracks sequential authorization failures over a sliding time-window configuration."""
    
    def __init__(self, failure_threshold: int = 3, lookback_ms: int = 60000):
        super().__init__(
            name="ruleset::authentication::brute_force",
            description="Detects multiple authentication failures targeting localized user accounts.",
            service="AuthService"
        )
        self.threshold = failure_threshold
        self.lookback_ms = lookback_ms
        self.state_lock = threading.Lock()
        self.user_tracking: Dict[str, List[int]] = {}
        
        self.templates["en"] = "Brute force pattern detected for user $username within domain $domain. Total failures: $count"

    def evaluate(self, log: SiemLog) -> Optional[Tuple[SiemAlert, Optional[Dict[str, Any]]]]:
        if log.event_type != "AUTH_FAILURE":
            return None
            
        username = log.get_field("auth.username")
        domain = log.get_field("auth.domain", "LOCAL")
        if not username:
            return None
            
        tracking_key = f"{domain}|{username}"
        current_time = log.timestamp
        
        with self.state_lock:
            if tracking_key not in self.user_tracking:
                self.user_tracking[tracking_key] = []
                
            history = self.user_tracking[tracking_key]
            history.append(current_time)
            
            # Prune events older than our window limit
            self.user_tracking[tracking_key] = [t for t in history if current_time - t <= self.lookback_ms]
            current_count = len(self.user_tracking[tracking_key])
            
            if current_count >= self.threshold:
                desc_tpl = self.get_localized_description(log.tenant, self.templates["en"])
                resolved_desc = (desc_tpl
                                 .replace("$username", username)
                                 .replace("$domain", domain)
                                 .replace("$count", str(current_count)))
                
                alert = SiemAlert(
                    alert_id=f"ALT-{log.log_id}-{int(time.time())}",
                    title="Suspicious Authentication Activity - Brute Force",
                    description=resolved_desc,
                    severity=AlertSeverity.HIGH,
                    creation_time=int(time.time() * 1000),
                    rule_name=self.name,
                    triggering_log=log,
                    mitre_tactics=["TA0001"], # Initial Access
                    mitre_techniques=["T1110"], # Brute Force
                    aggr_key=tracking_key,
                    aggr_limit=current_time + self.lookback_ms
                )
                
                # Request firewall or account lockout mitigation action
                mitigation = {
                    "action": "ACCOUNT_LOCK",
                    "target_user": username,
                    "target_domain": domain,
                    "expiry_ms": 1800000
                }
                return alert, mitigation
                
        return None

class PrivilegeEscalationRule(SiemRule):
    """Stateless analysis rule catching anomalous command execution strings."""
    
    def __init__(self):
        super().__init__(
            name="ruleset::privilege::execution_anomaly",
            description="Identifies dangerous process parameters executed by non-administrative sessions.",
            service="OS_Audit"
        )
        self.monitored_commands = {"chmod +x", "sudo su", "mimikatz", "vssadmin delete shadows"}
        self.templates["en"] = "High risk process execution string observed: '$command' spawned by session user '$user'"

    def evaluate(self, log: SiemLog) -> Optional[Tuple[SiemAlert, Optional[Dict[str, Any]]]]:
        if log.event_type != "PROCESS_SPAWN":
            return None
            
        cmd_line = log.get_field("process.command_line", "").lower()
        user_session = log.get_field("process.user", "unknown")
        
        matched_cmd = next((cmd for cmd in self.monitored_commands if cmd in cmd_line), None)
        
        if matched_cmd:
            desc_tpl = self.get_localized_description(log.tenant, self.templates["en"])
            resolved_desc = desc_tpl.replace("$command", matched_cmd).replace("$user", user_session)
            
            alert = SiemAlert(
                alert_id=f"ALT-{log.log_id}",
                title="Privilege Escalation Vector Identified",
                description=resolved_desc,
                severity=AlertSeverity.CRITICAL,
                creation_time=int(time.time() * 1000),
                rule_name=self.name,
                triggering_log=log,
                mitre_tactics=["TA0004"], # Privilege Escalation
                mitre_techniques=["T1068", "T1059"]
            )
            return alert, {"action": "ISOLATE_ENDPOINT", "host": log.get_field("host.hostname")}
            
        return None

# =====================================================================
# ENGINE: ROUTING & COORDINATION LIFECYCLE MANAGERS
# =====================================================================

class CorrelationEngine:
    """The orchestration runtime processing raw data logs against dynamic rulesets."""
    
    def __init__(self):
        self.rules: List[SiemRule] = []
        self.alert_callback_hook = None
        self.action_callback_hook = None
        self.processed_log_count = 0

    def register_rule(self, rule: SiemRule):
        self.rules.append(rule)
        logger.info(f"Rule matching component '{rule.name}' successfully mounted into engine.")

    def set_output_hooks(self, on_alert, on_action=None):
        self.alert_callback_hook = on_alert
        self.action_callback_hook = on_action

    def dispatch_log(self, raw_payload: str) -> int:
        """Parses, normalizes, and feeds logs through every registered rule signature."""
        try:
            parsed = json.loads(raw_payload)
            normalized_log = SiemLog(
                log_id=parsed.get("id", f"LOG-{int(time.time()*1000)}"),
                tenant=parsed.get("tenant", "default"),
                timestamp=parsed.get("timestamp", int(time.time() * 1000)),
                service=parsed.get("service", "GenericEngine"),
                event_type=parsed.get("event_type", "GENERIC"),
                payload=parsed.get("payload", {}),
                tags=set(parsed.get("tags", []))
            )
            
            self.processed_log_count += 1
            matches_found = 0
            
            for rule in self.rules:
                match_results = rule.evaluate(normalized_log)
                if match_results:
                    matches_found += 1
                    alert, mitigation_request = match_results
                    
                    if self.alert_callback_hook:
                        self.alert_callback_hook(alert)
                    if mitigation_request and self.action_callback_hook:
                        self.action_callback_hook(mitigation_request)
                        
            return matches_found
        except Exception as err:
            logger.error(f"Failed to ingest log stream event framework payload: {str(err)}")
            return 0